apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: dataproduct-deploy
  namespace: nais-analyse
spec:
  schedule: "55 * * * *"
  command:
    - "python"
    - "/app/dataproduct.py"
  resources:
    limits:
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  accessPolicy:
    outbound:
      external:
        - host: console.nav.cloud.nais.io
  envFrom:
    - secret: dataproduct-deploy
  gcp:
    bigQueryDatasets:
      - name: deploys
        permission: READWRITE
