apiVersion: nais.io/v1
kind: Naisjob
metadata:
  name: dataproduct-deploy
  namespace: nais-analyse
spec:
  schedule: "55 * * * *"
  resources:
    limits:
      cpu: "400m"
      memory: "256Mi"
    requests:
      cpu: "200m"
      memory: "256Mi"
  envFrom:
    secret: dataproduct-deploy
  gcp:
    bigQueryDatasets:
      - name: deploys
        permission: READWRITE
